### PR TITLE
Refer to #1 - Fix: Prevent exponential ball growth on multi-ball pickup

### LINKED ISSUE #1: Exponential ball growth with multiple Multi-Ball power-ups causes lag
The ball count doubles again (e.g., 1 -> 2 -> 4 -> 8), causing performance issues. This is because the code in script.js doubles all current balls, not just the original one:

```javascript
// script.js
case 'multiBall':
    if (gameState.balls.length < 5) { // This check is insufficient
        gameState.balls.forEach(ball => {
            gameState.balls.push({...ball});
        });
    }
```

### PR DESCRIPTION
**Pull request by alice-kk-admin**
This PR addresses the performance issues (exponential lag) caused when multiple multi-ball power-ups are active simultaneously. Previously, the logic doubled every existing ball on the screen, leading to an unmanageable number of entities.

The logic has been updated to add exactly two new balls per power-up instance, providing a balanced gameplay experience without crashing the game.

This might potentially fix #1

### CODE REVIEW

File: script.js [hunk 1]
```diff
@@ -370,10 +370,14 @@ function activatePowerUp(type) {
     
     switch(type) {
         case 'multiBall':
-            if (gameState.balls.length < 5) {
-                gameState.balls.forEach(ball => {
-                    gameState.balls.push({...ball});
-                });
+            if (gameState.balls.length < 3) {
```
Comment (msrevathi) [inline script.js]: please make sure the length is less than 4

File: script.js [hunk 2]
```diff
@@ -370,10 +370,14 @@ function activatePowerUp(type) {
...
+                // gameState.balls.forEach(ball => {
+                //     gameState.balls.push({...ball});
+                // });
+                // Add two new balls with slightly different trajectories
+    gameState.balls.push({ ...gameState.balls[0], dx: -gameState.balls[0].dx });
+    gameState.balls.push({ ...gameState.balls[0], dy: Math.abs(gameState.balls[0].dy) });
```
Comment (msrevathi) [inline script.js:379]: this looks good, i hope this was tested!

**Review by msrevathi — CHANGES_REQUESTED** [review]
please review my comments and make changes.
